// game.actors.filter(x => x.data.name == "GM Roller")[0]
// td[0].update({"img":"aouaou.jpg"},renderTemplate)
// td[0].update({"img":"mod.jpg","data":{"bio":{"note":{"value":"oaeaouoauoau"}}}},renderTemplate)

const escapedBreak = `\<br\/\>`;
//NAMES
elf_male = [
  "Abarat",
  "Adamar",
  "Adorellan",
  "Adresin",
  "Aelrindel",
  "Aerendyl",
  "Aeson",
  "Afamrail",
  "Agandaur",
  "Agis",
  "Aias",
  "Aiduin",
  "Aien",
  "Ailas",
  "Ailduin",
  "Ailen",
  "Ailluin",
  "Ailmar",
  "Ailmer",
  "Ailmon",
  "Ailre",
  "Ailred",
  "Ailuin",
  "Ailwin",
  "Aimar",
  "Aimer",
  "Aimon",
  "Airdan",
  "Aire",
  "Aired",
  "Aithlin",
  "Aiwin",
  "Akkar",
  "Alabyran",
  "Alaion",
  "Alas",
  "Alen",
  "Alinar",
  "Alluin",
  "Almar",
  "Almer",
  "Almon",
  "Alok",
  "Alosrin",
  "Alre",
  "Alred",
  "Althidon",
  "Alwin",
  "Amrynn",
  "Andrathath",
  "Anfalen",
  "Anlyth",
  "Aolis",
  "Aquilan",
  "Arathorn",
  "Arbane",
  "Arbelladon",
  "Ardreth",
  "Ardryll",
  "Arel",
  "Arlen",
  "Arun",
  "Ascal",
  "Athtar",
  "Aubron",
  "Aumanas",
  "Aumrauth",
  "Avourel",
  "Ayas",
  "Ayduin",
  "Ayen",
  "Ayluin",
  "Aymar",
  "Aymer",
  "Aymon",
  "Ayre",
  "Ayred",
  "Aywin",
  "Belanor",
  "Beldroth",
  "Bellas",
  "Beluar",
  "Biafyndar",
  "Bialaer",
  "Braern",
  "Cailu",
  "Camus",
  "Castien",
  "Chathanglas",
  "Cohnal",
  "Conall",
  "Connak",
  "Cornaith",
  "Corym",
  "Cyran",
  "Dain",
  "Dakath",
  "Dalyor",
  "Darcassan",
  "Darfin",
  "Darthoridan",
  "Darunia",
  "Deldrach",
  "Delmuth",
  "Delsaran",
  "Devdan",
  "Drannor",
  "Druindar",
  "Durlan",
  "Durothil",
  "Dyffros",
  "Edwyrd",
  "Edyrm",
  "Ehlark",
  "Ehrendil",
  "Eilauver",
  "Elaith",
  "Elandorr",
  "Elas",
  "Elashor",
  "Elauthin",
  "Eldaerenth",
  "Eldar",
  "Eldrin",
  "Elduin",
  "Elen",
  "Elephon",
  "Elidyr",
  "Elion",
  "Elkhazel",
  "Ellisar",
  "Elluin",
  "Elmar",
  "Elmer",
  "Elmon",
  "Elnaril",
  "Elorshin",
  "Elpharae",
  "Elre",
  "Elred",
  "Eltaor",
  "Elwin",
  "Elyon",
  "Emmyth",
  "Entrydal",
  "Erendriel",
  "Eriladar",
  "Erlan",
  "Erlareo",
  "Erlathan",
  "Eroan",
  "Erolith",
  "Estelar",
  "Ethlando",
  "Ettrian",
  "Evindal",
  "Faelar",
  "Faelyn",
  "Faeranduil",
  "Falael",
  "Felaern",
  "Fenian",
  "Feno",
  "Feyrith",
  "Fhaornik",
  "Filarion",
  "Filvendor",
  "Filverel",
  "Flardryn",
  "Flinar",
  "Folas",
  "Folduin",
  "Folen",
  "Folluin",
  "Folmar",
  "Folmer",
  "Folmon",
  "Folre",
  "Folred",
  "Folwin",
  "Fylson",
  "Gaeleath",
  "Gaelin",
  "Galaeron",
  "Galan",
  "Galather",
  "Ganamede",
  "Gantar",
  "Garrik",
  "Garynnon",
  "Giullis",
  "Glanduil",
  "Glarald",
  "Glorandal",
  "Goras",
  "Gorduin",
  "Goren",
  "Gorluin",
  "Gormar",
  "Gormer",
  "Gormon",
  "Gorre",
  "Gorred",
  "Gorwin",
  "Grathgor",
  "Haemir",
  "Hagas",
  "Hagduin",
  "Hagen",
  "Hagluin",
  "Hagmar",
  "Hagmer",
  "Hagre",
  "Hagred",
  "Hagwin",
  "Haladavar",
  "Halafarin",
  "Halamar",
  "Haldir",
  "Halflar",
  "Halueth",
  "Halueve",
  "Hamon",
  "Haryk",
  "Hastios",
  "Hatharal",
  "Horith",
  "Hubys",
  "Iefyr",
  "Ievis",
  "Ilbryen",
  "Ilimitar",
  "Iliphar",
  "Illianaro",
  "Illithor",
  "Illitran",
  "Ilphas",
  "Ilrune",
  "Ilthuryn",
  "Ilvisar",
  "Inchel",
  "Inialos",
  "Intevar",
  "Iolas",
  "Iolrath",
  "Itham",
  "Ivaran",
  "Ivasaar",
  "Iymbryl",
  "Iyrandrar",
  "Jandar",
  "Jannalor",
  "Jaonos",
  "Jassin",
  "Jhaan",
  "Jhaartael",
  "Jhaeros",
  "Jonik",
  "Jorildyn",
  "Kailu",
  "Katar",
  "Katyr",
  "Kellam",
  "Kelvhan",
  "Kendel",
  "Kerym",
  "Keryth",
  "Kesefeon",
  "Kharis",
  "Khatar",
  "Khidell",
  "Khiiral",
  "Khilseith",
  "Khuumal",
  "Khyrmin",
  "Kieran",
  "Kiirion",
  "Kindroth",
  "Kivessin",
  "Klaern",
  "Kolvar",
  "Kuskyn",
  "Kymil",
  "Kyrenic",
  "Kyrtaar",
  "Laeroth",
  "Lafarallin",
  "Laiex",
  "Lamruil",
  "Larongar",
  "Larrel",
  "Lathai",
  "Lathlaeril",
  "Lhoris",
  "Lianthorn",
  "Llarm",
  "Llewel",
  "Lorsan",
  "Luirlan",
  "Luthais",
  "Luvon",
  "Lyari",
  "Lyklor",
  "Lysanthir",
  "Maeral",
  "Maiele",
  "Malgath",
  "Malon",
  "Maradeim",
  "Marikoth",
  "Marlevaur",
  "Melandrach",
  "Merellien",
  "Merith",
  "Methild",
  "Mhaenal",
  "Mitalar",
  "Mihangyl",
  "Miirphys",
  "Mirthal",
  "Mlartlar",
  "Mnementh",
  "Morthil",
  "Myrdin",
  "Myriil",
  "Myrin",
  "Mythanar",
  "Naertho",
  "Naeryndam",
  "Naesala",
  "Narbeth",
  "Nardual",
  "Nasir",
  "Navarre",
  "Nelaeryn",
  "Neldor",
  "Neremyn",
  "Nesterin",
  "Nevarth",
  "Nhamashal",
  "Nieven",
  "Nindrol",
  "Ninleyn",
  "Ninthalor",
  "Niossae",
  "Nuvian",
  "Nylian",
  "Nym",
  "Nyvorlas",
  "Olaurae",
  "Onas",
  "Oncith",
  "Onvyr",
  "Orist",
  "Ornthalas",
  "Orrian",
  "Orym",
  "Otaehryn",
  "Othorion",
  "Paeral",
  "Paeris",
  "Pelleas",
  "Phaendar",
  "Pharom",
  "Phraan",
  "Pirphal",
  "Purtham",
  "Pyrravyn",
  "Pywaln",
  "Qildor",
  "Raeran",
  "Raibyn",
  "Ralnor",
  "Ranaeril",
  "Rathal",
  "Reluraun",
  "Reluvethel",
  "Rennyn",
  "Reptar",
  "Respen",
  "Revalor",
  "Rhalyf",
  "Rhangyl",
  "Rhistel",
  "Rhothomir",
  "Rhys",
  "Rilitar",
  "Riluaneth",
  "Rolim",
  "Rothilion",
  "Ruehnar",
  "Ruith",
  "Ruvaen",
  "Ruven",
  "Ruvyn",
  "Rychell",
  "Rydel",
  "Ryfon",
  "Ryo",
  "Ryul",
  "Saelethil",
  "Saevel",
  "Saleh",
  "Samblar",
  "Sanev",
  "Scalanis",
  "Selanar",
  "Sharian",
  "Shaundyl",
  "Shyrrik",
  "Sihnion",
  "Silvyr",
  "Simimar",
  "Sinaht",
  "Siveril",
  "Sontar",
  "Sudryal",
  "Sundamar",
  "Sylvar",
  "Sythaeryn",
  "Taegen",
  "Taenaran",
  "Taeral",
  "Taerentym",
  "Taleasin",
  "Tamnaeth",
  "Tanithil",
  "Tannatar",
  "Tannivh",
  "Tannyll",
  "Tanyl",
  "Tanyth",
  "Taranath",
  "Tarathiel",
  "Taredd",
  "Tarron",
  "Tasar",
  "Tassarion",
  "Tathaln",
  "Thalanil",
  "Thallan",
  "Theodas",
  "Theodemar",
  "Theoden",
  "Theodluin",
  "Theodmer",
  "Theodmon",
  "Theodre",
  "Theodred",
  "Thuridan",
  "Tiarsus",
  "Tolith",
  "Tordynnar",
  "Toross",
  "Traeliorn",
  "Travaran",
  "Triandal",
  "Ualiar",
  "Uevareth",
  "Uldreyin",
  "Urdusin",
  "Usunaar",
  "Uthorim",
  "Vaalyun",
  "Vaeril",
  "Vamir",
  "Varitan",
  "Velethuil",
  "Venali",
  "Vesryn",
  "Vesstan",
  "Virion",
  "Volodar",
  "Voron",
  "Vuduin",
  "Vulas",
  "Vulen",
  "Vulluin",
  "Vulmar",
  "Vulmer",
  "Vulmon",
  "Vulre",
  "Vulred",
  "Vulwin",
  "Wirenth",
  "Wistari",
  "Wyn",
  "Wyninn",
  "Wyrran",
  "Yalathanil",
  "Yesanith",
  "Yhendorn",
  "Ylyndar",
  "Zaos",
  "Zelphar",
  "Zeno",
  "Zhoron",
];
elf_female = [
  "Aelrie",
  "Aelua",
  "Aelynthi",
  "Aenwyn",
  "Aerilaya",
  "Aerith",
  "Ahrendue",
  "Ahshala",
  "Aila",
  "Alagossa",
  "Alais",
  "Alanis",
  "Alasse",
  "Alavara",
  "Alea",
  "Aleesia",
  "Alenia",
  "Aleratha",
  "Allannia",
  "Allisa",
  "Alloralla",
  "Allynna",
  "Almedha",
  "Almithara",
  "Alvaerelle",
  "Alyndra",
  "Amara",
  "Amaranthae",
  "Amarille",
  "Amedee",
  "Ameria",
  "Amisra",
  "Amnestria",
  "Amra",
  "Anarzee",
  "Aneirin",
  "Anhaern",
  "Annallee",
  "Ara",
  "Arasne",
  "Aravae",
  "Arcaena",
  "Ariawyn",
  "Arilemna",
  "Arlayna",
  "Arnarra",
  "Arryn",
  "Arthion",
  "Artin",
  "Ashera",
  "Ashryn",
  "Aurae",
  "Ava",
  "Axilya",
  "Ayda",
  "Ayla",
  "Azariah",
  "Baerinda",
  "Bellaluna",
  "Bemere",
  "Bonaluria",
  "Burolia",
  "Caeda",
  "Caerthynna",
  "Calarel",
  "Celaena",
  "Cellica",
  "Chaenath",
  "Chalia",
  "Chalsarda",
  "Chamylla",
  "Chandrelle",
  "Chasianna",
  "Ciliren",
  "Ciradyl",
  "Cithrel",
  "Clanire",
  "Cremia",
  "Daethie",
  "Daratrine",
  "Darshee",
  "Darunia",
  "Dasyra",
  "Delimira",
  "Delsanra",
  "Dessielle",
  "Deulara",
  "Dilya",
  "Dirue",
  "Ealirel",
  "Ecaeris",
  "Edea",
  "Edraele",
  "Eirina",
  "Elanalue",
  "Elanil",
  "Elasha",
  "Elenaril",
  "Eletha",
  "Elincia",
  "Elisen",
  "Eliyen",
  "Ellarian",
  "Elmyra",
  "Eloimaya",
  "Elora",
  "Elyon",
  "Ena",
  "Enania",
  "Eshenesra",
  "Esiyae",
  "Essaerae",
  "Esta",
  "Falenas",
  "Faraine",
  "Farryn",
  "Faunalyn",
  "Fayeth",
  "Faylen",
  "Fhaertala",
  "Filaurel",
  "Filauria",
  "Fildarae",
  "Finnea",
  "Gaelira",
  "Gaerradh",
  "Gaylia",
  "Geminara",
  "Ghilanna",
  "Glynnii",
  "Gweyir",
  "Gwynnestri",
  "Gylledhia",
  "Haciathra",
  "Haera",
  "Halaema",
  "Halanaestra",
  "Hamalitia",
  "Haramara",
  "Helartha",
  "Holone",
  "Huethea",
  "Hycis",
  "Ialantha",
  "Ikeshia",
  "Ildilyntra",
  "Ilmadia",
  "Ilsevel",
  "Ilyana",
  "Ilyrana",
  "Ilythyrra",
  "Imizael",
  "Immianthe",
  "Imra",
  "Imryll",
  "Ioelena",
  "Irhaal",
  "Isarrel",
  "Isilynor",
  "Ithronel",
  "Itireae",
  "Itylara",
  "Jastira",
  "Jeardra",
  "Jhaerithe",
  "Jhanandra",
  "Jhilsara",
  "Kali",
  "Kasula",
  "Kavrala",
  "Kaylessa",
  "Kaylin",
  "Keenor",
  "Keerla",
  "Keishara",
  "Kenia",
  "Kethryllia",
  "Keya",
  "Kilyn",
  "Kylantha",
  "Kythaela",
  "Laamtora",
  "Laerdya",
  "Lazziar",
  "Leena",
  "Leilatha",
  "Lenna",
  "Lensa",
  "Lethhonel",
  "Lierin",
  "Liluth",
  "Lithoniel",
  "Lixiss",
  "Llamiryl",
  "Llorva",
  "Loreleia",
  "Lura",
  "Lusha",
  "Lusserina",
  "Lyeecia",
  "Lyeneru",
  "Lymseia",
  "Lyndis",
  "Lyra",
  "Lyrei",
  "Lythienne",
  "Madris",
  "Maelyrra",
  "Maeralya",
  "Maescia",
  "Makaela",
  "Malonne",
  "Malruthiia",
  "Mariona",
  "Mathienne",
  "Maylin",
  "Meira",
  "Melarue",
  "Meorise",
  "Merethyl",
  "Merialeth",
  "Meriel",
  "Merlara",
  "Mhoryga",
  "Micaiah",
  "Minuvae",
  "Muelara",
  "Myantha",
  "Mylaela",
  "Mylaerla",
  "Myriani",
  "Myrrh",
  "Nabeora",
  "Naesala",
  "Naevys",
  "Naexi",
  "Nakiasha",
  "Nalaea",
  "Nambra",
  "Namys",
  "Nanthaliene",
  "Neia",
  "Nephinae",
  "Nimeroni",
  "Nimue",
  "Nithenoel",
  "Nithroel",
  "Nuala",
  "Nueleth",
  "Nuovis",
  "Nushala",
  "Nyana",
  "Nylathria",
  "Ochilysse",
  "Omylia",
  "Osonia",
  "Penelo",
  "Phaerille",
  "Phelorna",
  "Phinara",
  "Phyrra",
  "Pyria",
  "Qamara",
  "Radelia",
  "Raenisa",
  "Rallientha",
  "Rania",
  "Ratha",
  "Rathiain",
  "Renestrae",
  "Renna",
  "Rina",
  "Riniya",
  "Rophalin",
  "Rosanhi",
  "Rosaniya",
  "Roshia",
  "Rubarae",
  "Ryllae",
  "Saelihn",
  "Saida",
  "Sakaala",
  "Salihn",
  "Sana",
  "Saphielle",
  "Saria",
  "Sariandi",
  "Sarya",
  "Seldanna",
  "Selphie",
  "Selussa",
  "Shael",
  "Shaerra",
  "Shalaevar",
  "Shalana",
  "Shalendra",
  "Shalheira",
  "Shalia",
  "Shanaera",
  "Shandalar",
  "Shanyrria",
  "Shelara",
  "Shenarah",
  "Sillavana",
  "Sionia",
  "Siora",
  "Siphanien",
  "Siraye",
  "Solana",
  "Soliana",
  "Sorisana",
  "Sumina",
  "Syllia",
  "Sylmare",
  "Symania",
  "Syndra",
  "Syvis",
  "Taenya",
  "Talanashta",
  "Talindra",
  "Tanelia",
  "Tanila",
  "Tanulia",
  "Tarasynora",
  "Tehlarissa",
  "Tephysea",
  "Teriani",
  "Thaciona",
  "Thalia",
  "Thaola",
  "Thasinia",
  "Thessalia",
  "Tialha",
  "Tinesi",
  "Tiriana",
  "Tisha",
  "Tsarra",
  "Tyrael",
  "Ulesse",
  "Umilythe",
  "Uneathen",
  "Urricea",
  "Usamea",
  "Vaeri",
  "Valindra",
  "Vanya",
  "Vasati",
  "Velatha",
  "Verrona",
  "Vestele",
  "Vianola",
  "Viessa",
  "Wynather",
  "Yaereene",
  "Yalanue",
  "Yathanae",
  "Ygannea",
  "Ynaselle",
  "Yralissa",
  "Yrathea",
  "Yrneha",
  "Ysildea",
  "Yumanea",
  "Yunaesa",
  "Zaleria",
  "Zentha",
  "Zestari",
  "Zilyana",
];

//PATHS
const PATH_BASE = "modules/smoke-raven-foundry-vtt-forbidden-lands-scripts/";

// CONDITIONS
const COLD = `@UUID[JournalEntry.UafcV3qgAa4MhJGF.JournalEntryPage.SRRGpiNQmhdPmuA3]{COLD}`;
const HUNGRY = `@UUID[JournalEntry.UafcV3qgAa4MhJGF.JournalEntryPage.DYS2Fu0Xy13JMQ9a]{HUNGRY}`;
const OVERHEATED = `@UUID[JournalEntry.UafcV3qgAa4MhJGF.JournalEntryPage.dhSenBJ6zAixPfXo]{OVERHEATED}`;
const SLEEPY = `@UUID[JournalEntry.UafcV3qgAa4MhJGF.JournalEntryPage.isumMPE2xFWd4QV6]{SLEEPY}`;
const THIRSTY = `@UUID[JournalEntry.UafcV3qgAa4MhJGF.JournalEntryPage.ZsG1q6f3KQvZBeZN]{THIRSTY}`;
// SKILLS
const ANIMALHANDLING = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.CgeT1qstM2JPwq3o]{Animal Handling}`;
const CRAFTING = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.WWHbsAj6E0Bqtjll]{Crafting}`;
const ENDURANCE = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.3pvmh8oiYcii9Iua]{Endurance}`;
const HEALING = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.9CZzRvmdHYeZGhFg]{Healing}`;
const INSIGHT = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.zHgK0ESA21X5MuoQ]{Insight}`;
const LORE = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.mwx7MoTuWAIpXNMe]{Lore}`;
const MANIPULATION = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.tsGst4ZFdJKPZknR]{Manipulation}`;
const MARKSMANSHIP = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.h3miEd7uuBNuyFEb]{Marksmanship}`;
const MELEE = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.ctskl9HQcALf81EM]{Melee}`;
const MIGHT = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.L0q68t4mBMDLLYbv]{Might}`;
const MOVE = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.dFN6RtZ3YidyBY3g]{Move}`;
const PERFORMANCE = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.bcFNTQrmWnky2QYR]{Performance}`;
const SCOUTING = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.uhAkwJo0FTFo6QtB]{Scouting}`;
const SLEIGHTOFHAND = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.bcjn07t6MCINvFo3]{Sleight of Hand}`;
const STEALTH = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.Mi7gz2XH4hhP6Gdj]{Stealth}`;
const SURVIVAL = `@UUID[JournalEntry.lKdU21aZiIVU5CDe.JournalEntryPage.RPqVV4gyvV0Y9AqD]{Survival}`;
// ACTIVITIES
const EXPLORE = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.dKIB4OgNfNXMmHVU]{EXPLORE}`;
const FORAGE = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.o0grjduXWT4MDPZ3]{FORAGE}`;
const FISH = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.9mPlwMvsC6NM6uld]{FISH}`;
const HIKE = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.Qvc9MA5QUKds1znD]{HIKE}`;
const HUNT = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.cCfguLeDXL7YxkYl]{HUNT}`;
const KEEPWATCH = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.uB6lVB7IXdDkLV9c]{KEEP WATCH}`;
const LEADTHEWAY = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.xhBHfOF3E9AP09r9]{LEAD THE WAY}`;
const MAKECAMP = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.X9vsNxS7IS49MxIF]{MAKE CAMP}`;
const REST = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.ywuv3K5bu3lfrXyC]{REST}`;
const SEATRAVEL = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.mAhe1hTB0C9UgoqF]{SEA TRAVEL}`;
const SLEEP = `@UUID[JournalEntry.PhtWwbTDEPySV1hx.JournalEntryPage.QmGU2Hrncrr7Co2K]{SLEEP}`;
// NPCs
const HILLIS_IMG = `${PATH_NPC_NAMED}hillis-the-trader-portrait.jpg`;
const HILLIS_LOCATION = `@JournalEntry[5P31tTvLFsJGY0fa]{Hillis' Store}`;
const HILLIS_ACTOR = `@Actor[ADLjxZInt50VQGSe]{Hillis The Trader}`;
const OGRIN_IMG = `${PATH_NPC_NAMED}ogrin-tailor-northfall.jpg`;
const OGRIN_LOCATION = `@JournalEntry[1sJjnJblZlpdlzfh]{Ogrin the Tailor}`;
const OGRIN_ACTOR = `@Actor[yzm63qgUzLAysowV]{Ogrin The Tailor}`;
const CUSS_AND_DANG_IMG = `${PATH_NPC_NAMED}cuss-and-dang-portrait.jpg`;
const CUSS_AND_DANG_LOCATION = `@JournalEntry[1eUy2gKf0V35MdoQ]{Cuss and Dang's Inn}`;
const CUSS_AND_DANG_ACTOR = `@Actor[2CkFg6FjdH9jcOpp]{Cuss and Dang}`;
const CUSS_AND_DANG_MENU = `@JournalEntry[rMMz3TnjYyqmGhE6]{Cuss and Dangs Menu}`;
const HOLBENDA_IMG = `${PATH_BITTER_REACH}holbenda-blacksmith-portrait.jpg`;
const HOLBENDA_LOCATION = `@JournalEntry[MuHQmK4scrZBfAXZ]{Holbenda's Smithye}`;
const HOLBENDA_ACTOR = `@Actor[VfOBa833ctFmo6Y9]{Holbenda The Short}`;
//
// ENCOUNTERS
//
const encountersRoadside = [
  "A huge nest has fallen from a tree on the side of the road. The strange-looking eggs within seem on the verge of hatching.",
  "A dwarf falls from the sky onto the road with a splat. (Did a creature drop it, was he launched into the air, did he fall from a floating fortress?)",
  "A row of severed heads on spikes and a warning sign claiming, “Dis Rode Belong Negan”",
  "A very small goblin wearing an old carpet as a cape leaps into the path and demands tribute.",
  "A crazed halfling, starved out of his mind, jumps to the backs of the PCs and rips their packs apart with his teeth in search of food.",
  "A bounty hunter tracks his target.",
  "A lush garden is filled with ripe vegetables. It is protected by a magical ward, but what is triggered when entering the garden?",
  "A monstrous mount is ridden by a gnome. Friend or foe?",
  "Two guards hold a wanted poster. They carefully studies the party as they pass by.",
  "A smiling roadside merchant roasts rats, frogs, and squirrels on sticks. He offers a bite to the PCs.",
  "A chatty bard walks alongside the party. Time for an exposition dump!",
  "A bridle ties a well-groomed speckled horse to a nearby tree. The horse is fitted with an elegant but empty saddle. Who does it belong to? Do the PCs take it?",
  "A powerful storm forced you to take the only available refuge: an elderly couple’s home just off the side of the road. The two room home holds numerous open cups of the same pungent liquid.",
  "A naked bard asks for a lift to the nearest inn where he left his clothes and money.",
  "Alongside the road, a charlatan asks the party if they want to see a performance of his trained pets. The slightest affirmative answer causes Steve to give a whistle, and a huge swarm of ravenous locusts suddenly manifests.",
  "A fat friar hurries past the PCs mumbling, “It isn’t fair.”",
  "An evil wizard is tied to a stake, the body still smoking.",
  "Three young men work on tipping over an occupied outhouse.",
  "A band of orcs runs toward the party. They look over their shoulders and try to run through the party. Something dreadful has terrified them, and the party is heading in its direction!",
  "Traveling off the main road, the PCs feel like they are being followed. Who is hunting them?",
  "Three types of meat hang on a spit over a campfire. It is clear that it is three types of humanoids that hang over the flames.",
  "A snowy road hides a sinkhole that chutes the party on a slalom slide down the mountainside.",
  "A well-spoken bugbear wearing fine studded leather armor is trapped under a fallen tree. He begs the party to come to his aid.",
  "A ranger stops by the group’s camp one night and gives them advice on the trail ahead, including places to camp and a tavern where they can get good rates if they mention his name. All his advice is impeccable, but when they mention his name at the tavern, they’re told he died years ago on that very road.",
  "A shopping list for potions lies on the ground.",
  "The local baron has enacted a toll bridge. Several peasants were unaware, and cannot afford the toll. They beg the PCs for change.",
  "You find the remains of a pouch that contains coins fro ma land you do not recognize.",
  "The party hears a long stream of curses further up the road. Then they spot a head in the road. A person is still alive, buried up to his neck!",
  "An arrow hits a nearby trunk, a message wrapped around the shaft.",
  "A bridge is missing. Where it used to be is now a ferry service, for a sizable fee. The ferry looks like it might consist of bridge parts, and only takes a few travelers at a time.",
  "A loaded wagon travels down the road toward the party, but it has no apparent means of propulsion.",
  "As bandits attack, the PCs realize a friend of theirs is among the robbers.",
  "There is a mysterious flicker ahead, and one member of your party suddenly stops, paralyzed.",
  "Orcs gather twigs and berries along the road and it’s clear they have non-hostile purpose. Will the PCs attack just because they are orcs?",
  "A tree falls onto the road. Then a fireball blows up the tree. It appears the PCs are in the middle of a skirmish between druids and fire wizards.",
  "Flowers by the roadside turn their heads to follow the party, and they’re getting larger.",
  "An overturned beer cart lies in the road. Nearby, an enormous troll snores loudly, surrounded by empty kegs.",
  "A set of shackles lies at the side of the road.",
  "A village can be seen to the west. It isn’t on any of the maps.",
  "Three pilgrims trudge along the dusty road, an old man and two young men. Simple travelers? Or are they more than they seem?",
  "You stumble upon an old scroll case wedged between a tangle of tree branches. Inside is a village’s charter of rights and freedoms.",
  "A dead magic user clutches a scroll in his stiff hand. The scroll says something important.",
  "A single giant footprint lies along the path. There are no other signs of such footprints in the area.",
  "You party awakens to find all your gear has been stolen during the night. A quick search reveals twelve sets of tracks and, lying in the middle of your campsite, a smoldering pouch of herbs that, when you sniff them, make you feel slightly drowsy.",
  "An enormous dragon lands on the road in front of the group. It asks for directions to a certain village, gives the party a generous tip, and then flies off saying he intends to raze it to the ground.",
  "An exotic, almost alien weapon or tool lies on the side of the road.",
  "The PCs mysteriously repeat a piece of road they already passed, though the route has been perfectly straight to this point. The road even includes their footprints.",
  "A dozen townsfolk are running after a fleeing woman and attempting to stone her to death for being a prostitute.",
  "Two other adventuring groups are arguing in the middle of the road.",
  "You see a man-sized shadow from the left side of the road waving its arms at you. “Over here, quickly, I’ve caught one!”",
  "A person fleeing arranged marriage seeks refuge with the PCs.",
  "Picked mushrooms lay on stump to dry.",
  "A strange old man offers the PCs a scroll in a language they cannot read.",
  "Gnomes are holding a yard sale! They have any number of strange and fascinating contraptions.",
  "Someone has scattered caltrops across the road.",
  "You encounter a monk, a monkey, a turtle and a pig, all heading west.",
  "A weathered sign points off the road, yet with no apparent trail to follow.",
  "The next 1feet of road are covered with newly grown grass.",
  "Ladies clothing and under clothing are strewn in the bushes along the road. How did these get here?",
  "A formerly brilliant wizard, now pesters the party with the incoherent rants of a man driven mad by a botched invisibility spell.",
  "A drunken dwarf staggers along, challenging everyone to a wrestling match.",
  "A goblin, on fire, runs shrieking past the party.",
  "A rock with an odd, glowing rune sits by the road ahead.",
  "A noble, disguised as a filthy beggar, tests the party’s compassion and generosity. If they pass whatever standard he sets, then he becomes a source of various quests that require personal sacrifice to accomplish.",
  "A circus is set up alongside the road. A barker on the roadside cajoles you to “come inside and see what wonders it holds.”",
  "The road crests a hill, and spread out before the group is a stunning, sweeping vista of the land beyond. A painter sits nearby, capturing the scene, and asks the group to pose for his foreground.",
  "An overturned rowboat sits on the side of the road. There is no river or stream nearby. Under the rowboat is an entrance to a lair.",
  "A wandering cleric begs the heroes to recover a relic for them.",
  "A road sign saying where you came from is ahead of you.",
  "A group of guardsmen hang wanted posters on trees. One face looks familiar to a PC.",
  "A carriage is stuck high up in a tree.",
  "In the morning while breaking camp, the PCs spot a bush that wasn’t there before.",
  "A beautiful woman, adorned in the robes of an enchantress, emerges from hiding near the road and implores you to lend her aid.",
  "The road is lined with snakes sleeping in the sun.",
  "A necromancer uses his talents to animate animal and human corpses and forces them to perform in a roadside circus. The townsfolk from a nearby village seem to enjoy the show a bit too much.",
  "A chain gang digs ditches beside the road.",
  "A traveling minstrel challenges the wisest looking member of the party to a storytelling contest.",
  "A wizened tinker sells charms from his cart: dried frogs, finger bones, cat skulls, and the like. Leaving him, you turn to find he is eerily out of sight altogether.",
  "A paladin of a holy church and his retinue have ridden out on a holy crusade against evil and demand others who serve the cause of good to join their cause on the spot.",
  "The road starts to get muddy. Soon the mud is two feet deep. Water in the ditches alongside starts to bubble.",
  "A majestic elk sprints past with something golden caught in its antlers.",
  "A stranger on the road tells each PC to repent of their sins. He knows details.",
  "A door stands beside the road, but there is no sign of the rest of the house.",
  "A wine merchant’s wagon has shattered a wheel and he offers passers-by cut rate prices on his wares as it is getting repaired.",
  "An ugly old woman struggles to bring her wash basket of wet clothes up from the creek to the road. She stumbles and drops the laundry back down the slope.",
  "A monk, collapsed and bleeding on the roadside, pushes an unremarkable ring into a PC’s hands and desperately whispers, “You must…” before exhaling his last breath.",
  "A lost gnome asks for directions.",
  "A dead raven lies on the road, pierced by a bright blue fletched arrow.",
  "A table on the roadside holds a large basket of fresh vegetables. A sign reads “1 copper a bunch: honesty is a virtue!”",
  "You find a small leather bag. It smells of moisture, and contains a set of keys and a vellum map to the location of a small keep.",
  "The road is littered with bear traps.",
  "A thick fog has settled on the bridge ahead.",
  "The group arrives late at night at a tiny village straddling the road. They secure accommodation and food from the friendly locals and fall asleep. In the morning the village is empty and ruined, as if abandoned years ago.",
  "As the road passes through a hilly region, you spy a cave, from which can be heard the voice of a singing female.",
  "As you turn the corner, a dwarf and elf are standing over a stack of goblin corpses. They argue over the kill count.",
  "The party notices a sudden and drastic change in temperature, then just like that, things are back to normal.",
  "A little girl is watching you from just off the road. The next time you glance over, you see a wolf run away.",
  "An ecstatic farmer presses a cigar into your hands and proclaims, “It’s a girl!”",
  "Scratched into the dust of the road are the words, “Good luck tomorrow. You’re going to need it.”",
  "The entire party suddenly loses their bearings and realize that they’ve walked the same mile three times. Are they road weary or are they caught in something manipulating them.",
];
const encountersCity = [
  "A necromancer is using magical means to stuff the ballot box in favor of a particular mayoral candidate in town. The PCs are asked to find the culprit behind the fraudulent votes.",
  "A small orphan girl is terrified and shares a wild story about another child at the orphanage who is biting everyone.",
  "A severed head rolls down the center street. Attached is a warning sign that reads, “Dis Town Belong Negan.”",
  "Farmers just outside of town are panicked because a coven of hags have been burying dead owlbears under piles of cow manure. But why?",
  "A child asks the PCs to help him find his pet dog. But this simple task leads them somewhere where they don’t belong.",
  "A bounty hunter tracks his target.",
  "A noble’s home has delicious apples drooping just over the gate. The house is protected by a magical ward, but what is triggered when a single apple is taken?",
  "A monstrous mount lumbers into town. It is ridden by a gnome.",
  "Two guards hold a wanted poster. They carefully study the party as they pass by.",
  "A smiling merchant roasts rats, frogs, and squirrels on sticks. He offers a bite to the PCs.",
  "A chatty bard walks alongside the party. Time for an exposition dump!",
  "A group of kobolds found a home in the sewers beneath an alchemist’s shop. The chemicals have done strange things to them…",
  "An attractive maiden flirts with you. Her very large husband notices.",
  "A naked bard asks for directions to the nearest inn where he left his clothes and money.",
  "While haggling in the market the PCs notice people vanish for a few heartbeats then reappear. Nobody finds it strange",
  "It is the Annual Wyvern Race. The PCs are recruited as substitute racers for a down-on-their luck faction after a mysterious “accident” disabled the previous team.",
  "An evil wizard is hanging from the gallows, the body still smoking.",
  "Three mischievous children work on tipping over an occupied outhouse.",
  "An overweight town guard, panting heavily, chases someone who nears the PCs.",
  "The PCs feel like they are being followed as they stroll through the docks. Who is hunting them?",
  "Something goes wrong during a magical performance by a gnome mage. A simple trick summons a beast from another dimension and it attacks the audience and PCs. Is the gnome responsible of is there a more sinister actor pulling the strings?",
  "A back alley hides a sinkhole that chutes the party on a slalom slide down into the old pirate’s cove hidden beneath the city.",
  "A goblin statue is submerged just off the docks. But why?",
  "A bar patron gives the party advice on a quest. All his intel is impeccable, but when they mention his name at the tavern, they’re told he died years ago.",
  "A shopping list for potions lies on the street.",
  "The local baron has enacted a toll bridge to enter town. Several peasants were unaware, and cannot afford the toll. They beg the PCs for change.",
  "The PCs are hired to transport live cargo to the house of a noblewoman. One gets fed after midnight.",
  "A PC gets a frantic message from a family member and there is a race around town to find them.",
  "An arrow strikes the shop sign just above you, a message wrapped around the shaft.",
  "A noble is offended by a PC’s behavior (How dare you!?!) and challenges the PC to a duel at dawn.",
  "A loaded wagon travels past the party along Main Street, but it has no apparent means of propulsion.",
  "Ruffians attempt to shake the PCs down in an alley. The PCs realize a friend of theirs is among the robbers.",
  "There is a mysterious flicker, and one member of your party suddenly stops, paralyzed.",
  "An owlbear makes its nest in the horse stables. It’s only trying to protect its eggs.",
  "A fireball erupts from a home, blowing up a water barrel, generating a cloud of mist. It appears the PCs are in the middle of a domestic dispute between partners, one a wizard and one a sorcerer.",
  "Dozens of oozes are floating in the bay, blocking ship traffic. How did they get there?",
  "The PCs must babysit the teenage daughter of the mayor and she’s always looking for trouble.",
  "A set of shackles lies outside the city jail.",
  "The PCs go looking for a job, but a worn out shop owner presses the deed into their hand and says, “I’m over it. It’s yours!”",
  "Two gangs of goblins are seen marching towards the city from opposite directions, one wearing red sashes, the other blue.",
  "The local wizard tower is glowing orange.",
  "A powerful fighter hires the characters to lock him up for the night. He has contracted lycanthropy and is afraid he will do something he will regret. He is also afraid the pack that infected him might come to find him.",
  "A storyteller tells a random story about a creature from an exotic “Monster Guide Book.” The creature suddenly appears from around the corner!",
  "Upon returning to your room at the inn, you discover a body on the floor with a dagger just adjacent. You hear guards storming up the stairs.",
  "An enormous dragon lands in the street in front of the group. It asks for directions to a certain farmstead just outside of town. It gives the party a generous tip, then flies off saying he intends to raze it to the ground.",
  "As the party wanders, a surly fellow approaches: “We don’t like yer kind here!”",
  "A tavern owner captured a troll. Patrons are paying 5GP to ‘rastle it.",
  "A dozen townsfolk are running after a fleeing woman, attempting to stone her to death for being a prostitute.",
  "Two other adventuring groups are arguing just outside the tavern.",
  "You see a man-sized shadow just around the block waving its arms at you. “Over here, quickly, I’ve caught one!”",
  "A prominent businessman, well-known as honest and good-natured, disappears. The PCs stumble across his body, tattooed with symbols of an evil deity. Was he a cult’s victim or a member?",
  "The city’s renowned chocolateer has gone missing! The rewards for his safe return are substantial. If only there was a trail to follow…",
  "A plague of rats has befallen the best bakery in town. A fat and greedy wererat can’t resist nightly visits in rat form to gorge himself on the delicious treats.",
  "Gnomes are holding a sidewalk sale! They have any number of strange and fascinating contraptions.",
  "A little kid falls in front of a charging stagecoach.",
  "A cleric accuses the mayor of being a silver dragon.",
  "A rare cockatrice egg has gotten mixed into a market shipment and sold to an innkeeper. Anyone who eats it is liable to turn into stone! Trouble is, there are taverns in the city and it is almost time for breakfast…",
  "An enemy named Bauer has placed magical bombs throughout the city. The PCs need to find them and eliminate them within hours.",
  "Ladies clothing and under clothing are strewn just outside the doors of the PCs room at the inn. How did these get here?",
  "A young woman approaches the PCs, insisting one of the party is her husband who went missing two years ago. The other townsfolk agree, despite the PC not knowing her.",
  "Some hapless citizen is harassed by a ruffian named Biff. Will the characters step in to save him?",
  "The characters recognize the mayor’s son climbing out of a disreputable two-story building.",
  "Reports come in about a ghost haunting a dark alley in a city, and anyone investigating the ghost ends up dead. The story is an elaborate hoax created to keep people away while crooks are attempting to break into a vault of a nearby building.",
  "A famous adventurer was hurriedly approaching the PCs, yet he dropped dead mid-stride. Why was he coming toward your table?",
  "A circus is set up just outside of town. A barker cajoles you to “come inside and see what wonders it holds.”",
  "A group of young, rude nobles are racing horses through the streets and nearly ride down the characters. How the party handles this situation will determine how well they are received by the various factions in that city.",
  "A PC sees a beautiful woman sunbathing on a nearby rooftop. He’s spotted and waved over.",
  "Rumor has it there is an underground fight club in the warehouse district. They’ve been tasked with finding it and shutting it down. But will they want to join instead?",
  "The tavern owner’s daughter is missing and he’s offered you all the whiskey you can drink if you can bring her home safely. Turns out, she’s the ringleader of a gang.",
  "Townsfolk have been reporting sightings of strange creatures around town. But when questioned about it the next day, it’s like they didn’t see anything.",
  "It’s impossible to start a fire within the city walls. The most powerful mages, flame eidolons, and candlemakers have tried until they’re blue in the face; it just won’t catch. A clan of frost trolls has taken up residence nearby, but it can’t be THAT simple, can it?",
  "You arrive in town to find that hobgoblins have taken over. They’ve crudely replaced the mayor and subjugated the townspeople, but they also control the soldiers under threat of destroying families.",
  "A new healer has come to town, the most grievous wounds are healed good as new. Unfortunately, he’s a charlatan clouding the victims mind so they only think they’re back to full health. The wounds still exist and it’s only a matter of time until they flare up again…",
  "The great oak in the town square has blossomed leaves of tremendous color. Magenta, azure, and puce adorn its branches. Which would be great, except birds refuse to roost among the leaves, and it’s giving off a foul odor.",
  "A young boy has gone missing from his home. Everyone assumes him dead, except his mother swears she can still hear him. Turns out, there’s a tunnel system under the city where a creature is holding him hostage.",
  "Once a year a colorfully clothed benefactor sneaks into town under cover of night and leaves trinkets for the children of the town. The town must provide an annual offering to keep the benefactor from collecting a decidedly darker form of payment.",
  "A traveling minstrel challenges the wisest looking member of the party to a storytelling contest.",
  "Midsummer’s Eve has arrived, and flowered crowns are all the rage. The Fae always come to help celebrate, but the celebration comes and goes without any sign of them. Three days later, a battered brownie covered in frost stumbles through the gates and mutters something about Eternal Winter before collapsing. Snow begins to fall.",
  "A new song is gaining popularity in the taverns and music halls of the city, far from being a listening experience only, listeners also experience hallucinations. Every time they hear the song the visions get more vivid until they become so real the listener is whisked to a different plane entirely.",
  "A legendary paladin renowned for victory in battle and training many acolytes has gone missing, seemingly having turned their back on the order. Can they be found again in a time of need?",
  "A great northern city is experiencing rising temperatures. Creatures outside of town are shedding every bit of their white fur due to the unprecedented temperatures, their pitch-black skin beneath becoming exposed, causing them to appear unnatural, as if they’re living shadows. Meanwhile, they grow lean and bony, ever more wraith-like. Now, the shadow creatures are moving toward town, setting their ebony gaze on the thing they blame for this calamity—us.",
  "A tavern patron tells the PCs to repent of their sins. He knows details.",
  "A man calling himself “The Shoveler” has moved into town, assuming the position of chief caretaker of the local cemetery. But judging by what he’s digging up, does he shovel too well?",
  "A local hero named Gjallerabru is famed for standing alone against an invading horde. But it appears that he somehow cheated death, because death’s emissary has come a lookin’.",
  "When a wagon carrying a gigantic cage rolls up into town, the people are struck with curiosity. But when the tarpaulin is removed, there is only a strikingly cute turtle. “Thing’s vicious. Don’t let those enticing eyes fool ya. And don’t look at it too long.”",
  "The candles in town WON’T GO OUT. Every bit of flame becomes perpetual and any fires need to be completely quenched or else they will reignite. This is leading to problems, not just for infrastructure, but for the Mage’s College, where experiments are more delicate.",
  "The town tax collector has been kidnapped. Curiously enough, all of his gold was left behind; whoever took him wanted the man, not the money…",
  "When the armor and weapons at the blacksmith’s forge suddenly become animated, the surrounding area evacuates. A particularly large suit of armor shouts, “I shall defend my birthplace!”",
  "Shiny objects have been disappearing all over town. There seem to be an awful lot of crows hanging around lately, but it couldn’t possibly be them. Could it?",
  "When the three capstones begin to glow brightly, the Order of the Scarab becomes nervous. The stones haven’t lit up in centuries, and they had assumed the danger had passed…",
  "One of the town wells allegedly has curative properties. It has caused the gradual expansion of the walls to the point where some citizens have taken to living down there.",
  "The town gallows hasn’t been used in decades, but one morning a swollen noose is found swinging from the beam. When the rope-maker is found to be missing, the plot only thickens…",
  "The group arrives late at night at a tiny village. They secure accommodation and food from the friendly locals and fall asleep. In the morning the village is empty and ruined, as if abandoned years ago.",
  "Under the bridge downtown, a body has been found. Exotic spices and peppers surround the crime scene.",
  "When a strange island floats into view, the town is torn about investigating it. The sailors are eager to explore the new land, but the shaman warns against rushing in too hastily.",
  "There’s a new face in town. Or at least…a new figure. You haven’t been able to see their face. In fact, nobody has. Their lavender cloak is pulled tight to conceal their features while they whisper, “The Firestorm is nigh.”",
  "A little girl is watching you from the alley. The next time you glance over, you see a wolf run away.",
  "The local innkeeper has baked the MOST DELICIOUS strawberry rhubarb pie. Nobody can stop eating once they start.",
  "A note slides under the door of your room. On it are the words, “Good luck tomorrow. You’re going to need it.”",
  "An ecstatic shop owner presses a cigar into your hands and proclaims, “It’s a girl!”",
];
const encountersForest = [
  "A flutter of crimson butterflies blocks the dirt path to the creek, going into a maddening frenzy whenever someone approaches. Suddenly, the butterflies then open and close their wings, spelling out the word “Teeth” before flying away.",
  "The local alchemist has been discarding expired potion bottles by mixing them into his garden compost and dumping them into the stagnant pond behind his house. Not only are the crops gigantic, but the pond’s surface is a thick sludge. Now a large bubble is rising to the surface…",
  "In the middle of a deep forest, a well sits among what appears to have once been a lovely glade. Now, the trees around it are dying and rotting on the spot, and light appears to struggle to reach the glade.",
  "Local children have been going missing. They’re found wandering on the edge of the woods. They seem altered somehow and they tell stories of a witch who has been using them in her strange magics.",
  "A child asks the PCs to help him find his pet dog. But this simple task leads them somewhere where they don’t belong.",
  "A bounty hunter tracks his target.",
  "A homestead has delicious apples drooping just over a fence. The house is protected by a magical ward, but what is triggered when a single apple is taken?",
  "A monstrous mount lumbers across the trail. It is ridden by a gnome.",
  "The local potentate has declared a hunting contest. There is a rare elusive creature inhabiting the local forest. They offer a reward for proof of its destruction. However, a mysterious visitor to the area is offering an equal reward for keeping it safe.",
  "A smiling stranger roasts rats, frogs, and squirrels on sticks. He offers a bite to the PCs.",
  "A chatty bard runs across the party. Time for an exposition dump!",
  "There have been threats against a local noble. They require an escort to get them safely through the mysterious forest to the next larger town.",
  "Goblin hovels are popping up throughout the woods. Investigation yields that they’re all interconnected with a complex network of tunnels, and one tunnel goes much deeper underground than the rest…",
  "A naked bard asks for directions to the nearest inn where he left his clothes and money.",
  "A mischievous Boggle has taken up residence in a small valley where locals pick herbs and plants for potions and magical components. Though the pranks the Boggle has been employing have been mostly harmless, things are changing…",
  "Lizardfolk have been seen carving strange runes into the trees of the forest. No one has been able to decipher their meaning.",
  "An evil wizard is found slumped against a tree, the body still smoking.",
  "An old man from a local village recently murdered his wife in cold blood, screaming that, “The trees told me to do it. The trees!” Three days later, a young farm girl whispers, “The trees speak and I listen.”",
  "A door has appeared in the base of a mighty willow tree. The door has been locked for centuries, but one morning the door is wide open. Is it an invitation to enter? Or did something exit?",
  "The PCs feel like they are being followed as they stroll through the woods. Who is hunting them?",
  "A small village has reported that small fissures have opened up in the ground in the local forest. Stories of Drow patrols at night, once used to frighten children, now give all ages pause. A brash, famed spelunker left ten days ago to explore one of the new caves, but has not returned.",
  "A pile of brush covers a sinkhole that chutes the party on a slalom slide down into old pirate’s tunnels.",
  "As you walk down a forest trail, you hear whistles that repeat throughout the trees. When a member of your party steps off the trail, the whistling stops.",
  "There is a traveling caravan of halflings making its way through the valley. They sell trinkets, put on plays, and tell delightful stories and sing songs for a small fee. It’s really quite fun. And yet, there’s something odd about their impromptu camp at night.",
  "A shopping list for potions lies on the forest floor.",
  "There is a traveling forest of saplings making its way through the valley. When asked, the sentient trees communicate that they’re the first in the ‘Great Merging of the Old Trunks.” Suddenly, reports begin filtering in of other, more mature forests uprooting and moving locations.",
  "The PCs are hired to transport live cargo through a dusky forest trail. One gets fed after midnight.",
  "A mysterious bench has appeared on the edge of the forest, pointing towards the trees. A small box rests on top of the bench, filled with deliciously sweet confections and a note that reads: “Life.” Eating one provides a random magical effect–who put these here?",
  "An arrow strikes a tree trunk just above you, a message wrapped around the shaft.",
  "Autumn arrives, but none of the leaves have changed color. In fact, new shoots and buds are growing from the branches. The increased foliage becomes thick enough to allow walking on the canopy, leading to some people setting up residence atop the trees. What will happen when winter arrives?",
  "The local forest beekeeper is searching for some rare hybrids that lie deeper within the forest. Rumor has it that they will make the best honey in all the land, but they are incredibly poisonous.",
  "As the party walks down a rather wide trail, they are suddenly struck by the overall quiet. Then they look back, and realize that the path behind them has been covered by near impenetrable Forest growth. It was seemingly instantaneous, and what’s worse is that the path seems to be narrowing. Ahead, you see a strange, green fire.",
  "There is a mysterious flicker, and one member of your party suddenly stops, paralyzed.",
  "An owlbear makes its nest in the brambles. It’s only trying to protect its eggs.",
  "Foragers from a secluded village found human remains in a nearby swamp a few weeks ago. The villagers buried the remains following their funeral rites and customs. However, they now report that the spirit of a young lady haunts the village. It doesn’t appear to be malevolent, but the villagers are frightened and unnerved by her presence.",
  "After the horrific Firestorm, the landscape is left scarred and battered. In the valley, the rocks have been carved away, leaving a slender bridge in its wake. When peering through one side, the valley is lush with greenery.",
  "The Burned Path is only ‘ablaze’ for three days in the year. During that time, dozens of hopefuls attempt to traverse the intensely blazing leaves. At the end of the path is a hot springs occupied by a powerful Efreeti named Iripir. Would you seek her blessings?",
  "The Emerald Wall seems to be endless. Fog covers the end on the horizon but never subsides. What could possibly be contained behind its foliage?",
  "There is a forest where few dare to tread. People leave its borders feeling weak and sapped of strength, while the trees appear more vibrant. During the autumn, the leaves have such a concentrated blood-red hue…",
  "We woke up one day and the world was different. Vibrant. Surreal. Like everything was painted with an intricate brush. And the sky…blazing. The color of an overripe melon. What happens when the stars have no need of sleep?",
  "As the war raged, it became difficult for Sersia to find a safe haven. Her resources were running low, especially with the horse. But her cargo was precious, and nobody could find out that she was bringing it to the revolutionaries.",
  "There is a mighty oak known as the Sacred Eye. People from all over the world make pilgrimages to have their future told by the wise tree. The prophecies always come true, just not always for the person asking.",
  "The forest has crept and expanded, consuming all nearby structures except one. A deep thrumming can be heard as you approach, and the vines struggle to maintain their grip on the loose stones.",
  "At the peak of the World’s Palm, the rock stretches upwards like a sprawling tree, melding into the heavens. Nobody has dared climb into the swirling branches, but the potential for great power beckons.",
  "In the middle of a forest, it is said, stands a man made of Stone. Carved from Nature’s Cradle, he watches in silent vigil and guards the birthplace of the natural spirits.",
  "The Fractal Woods are a kaleidoscope of chromatic reflections, but after the sun sets, the only thing reflected is the darkness…",
  "Just outside town, the ground has sprouted an endless sea of purple flowers that ripple in the breeze. When you investigate, however, you realize that these aren’t blossoms; they are millions of tiny, floral creatures huddled in unison.",
  "Legend tells of the Tarnished Tree, a towering spruce encased perfectly in gold. Metal rusts when it gets too close, and many have died attempting to claim its riches…",
  "The Emerald Knight is revered and respected by all. He approaches the party and offers to pay them handsomely if they complete a quest…in his name. Should his credibility be questioned?",
  "You see a man-sized shadow just up the trail waving its arms at you. “Over here, quickly, I’ve caught one!”",
  "Deep within the forest, legend tells of a beast that rules with an iron hoof. It is said that when the time comes, he shall lead the wilderness in an uprising against hunters, trappers, and all who invade the woods. Several people are missing.",
  "When a strange fruit grows on a nearby tree, the town is torn between eating it or burning it. You feel an unnatural craving for the colorful flesh…",
  "Every seed that is planted grows into corn. Tomatoes, beans, strawberries – no matter how close an eye is kept on the ground, only corn emerges. It’s exceptionally delicious, but it is a curious thing.",
  "Strange vines have begun constricting the foliage at the oasis, and the plants begin to wither. Voices are coming from within, whispering words about broken promises and false friends.",
  "There is a place where two roads meet and everything is just a little more pale on one side versus the other. Greener grass, bluer skies, and clearer streams. What could be causing such a vast vibrancy difference?",
  "An ancient tree once stood next to the smithy, but overnight it was sucked into a giant sinkhole.",
  "A local lumberjack started chopping down a new area of forest. Every tree is completely hollow.",
  "This is the mysterious Tanglewood, a place inhabited by fae and ruled by their Queen, Ilysare. She is a prolific expert in dreamweaving and the subtle art of suggestion.",
  "There’s a witch living in an edible house in the middle of the woods. Further investigation reveals the house to be alive, and she’s merely a prisoner.",
  "A voice whispers softly next to your ear, “The Great Slumber shall soon be upon us.” You look around, but the only living thing nearby is a tiny butterfly, fluttering lightly on the breeze.",
  "All of the tree limbs are growing straight vertically towards the sky. Sunlight pierces the canopy, creating thick columns between the trunks.",
  "Alleged bandits have created a small community of tents in the forest. They have very low internal crime, and the mayor wants you to learn their secrets.",
  "Rumor is spreading of a huge centipede that’s been devouring wolves and deer. It hides in the forest, sleeping by day.",
  "Instead of yielding abundant crops, a varying assortment of flowers blanket the farmers’ fields. When burned, they regrow overnight.",
  "There’s an invisible wall on the forest path. Once you pass through it, you can’t seem to go back – some kind of curse. People on the original side can’t see or hear you. Better find a way to break this barrier!",
  "Don’t go into the woods alone. There are stories…people see things in the birch trees. Their trunks shift and sway; it’s not natural. And sometimes…sometimes the people don’t return. All that’s left is the chattering of teeth…",
  "Every year the animals migrate. Not because of climate or predators, but for an annual meeting in the mountains. They always follow the same path, a bright orange trail that cuts through the tall grass.",
  "A tree trunk blocks the forest path. Its diameter isn’t wide, but it’s unnaturally heavy and hard to move.",
  "An intelligent group of squirrels have learned how to use slings and they’re throwing stones at anyone entering their domain without permission.",
  "Harvesting season for the apple grove is full swing. Workers from all over have come to get their seasonal coin before the chill of late fall turns into winter. Peaceful Kobolds and Goblins are not uncommon among the workforce. However, a group of local ruffians are threatening to ransack their camp because they don’t want “their kind” here.",
  "A faction of dryads is in the middle of a war, making the forests extremely dangerous and stifling trade routes.",
  "A human druid Alic Hokkland died in a mysterious alchemical fire in the swamp a couple of years ago. Since then, strange rumors throughout the forest suggest a woodland swamp creature protects, or haunts as some suggest, the bog where Hokkland met his demise. A local logger has put out a bounty for killing the creature.",
  "Rainclouds are perpetually located over a section of the forest, but the raindrops never reach the forest floor. The local wizard, Quinnup assumes portal hi-jinx, but is too afraid to investigate.",
  "The great oak has blossomed leaves of tremendous color. Magenta, azure, and puce adorn its branches. Which would be great, except birds refuse to roost among the leaves, and it’s giving off a foul odor.",
  "A young boy has gone missing from his farm. Everyone assumes him dead, except his mother swears she can still hear him. Turns out, there’s a tunnel system under the farm where a creature is holding him hostage.",
  "The nearby forest has begun to glow. Oddly enough, the blacksmith’s forge is filled with sap. And is that…syrup you smell?",
  "When an ancient jade mask is excavated from a long-forgotten burial site, the archaeologists are perplexed. Everyone who has held it up to their face has been plagued with bouts of delirium and memory loss.",
  "A pack of wolves has taken in a young girl to raise as one of their own. They’re highly sophisticated, using silverware and everything.",
  "The swamps have begun bubbling incessantly, and the waters are warm to the touch. It’s driving the frogs and dragonflies away, but something peculiar lurks in the deep and the dark.",
  "A fish wriggles about on the forest path. Nobody is sure where it came from, but it’s definitely alive.",
  "A northern forest is experiencing rising temperatures. Creatures are shedding every bit of their white fur due to the unprecedented temperatures, their pitch-black skin beneath becoming exposed, causing them to appear unnatural, as if they’re living shadows. Meanwhile, they grow lean and bony, ever more wraith-like. Now, the shadow creatures are moving toward town, setting their ebony gaze on the thing they blame for this calamity—us.",
  "Pine cones have been replaced by rare and exotic fruit. It’s unusual and unexpected, but word is spreading and merchants are flocking to the area to lay claim to the rare goods.",
  "The local woodsmen have complained about breaking their axes far more frequently than usual. The tree bark is hearty and they’re denting the axe heads every other day.",
  "A message in a bottle washes up along the forest stream. It contains a map to a legendary treasure, but the starting location isn’t clear at all.",
  "A tribe of Treants has invaded nearby settlements, stripping them of their bricks and wood. A new, more natural city, is being erected in the forest with their spoils.",
  "As your party approaches a clearing, they are met by a group of what they initially thought to be wild horses. Upon closer look, these horses are all wearing saddles. One saddle still has what appears to be a human leg attached.",
  "An earthquake creates a huge fissure through the center of the forest, revealing a hidden valley filled with lush greenery. Scores of dinosaurs call this valley home.",
  "A local trapper has reported sightings of several will-o-wisps out in the swamps. They coincide with recent disappearances in the area. She is very protective of what she’s targeting with her traps.",
  "Every years, the owl conclave meets to discuss matters of the forest. It’s supposed to be happening tonight, but the only possible sign of the owls is a substantial pile of dead mice stacked up on the path.",
  "When the moonlight shines on a specific section of trees, they appear to be rotten and dead.",
  "A long line of cows tied together are wandering aimlessly through the forest. There haven’t been any reports of missing livestock, and their brand isn’t recognizable.",
  "Famine has struck the land and hunters are disgruntled. Suddenly, hordes of animals come pouring from the trees, abject horror reflected on their faces.",
  "A talking parrot squawks on the edge of the trees, complimenting everyone who comes near.",
  "Thirteen leaves are arranged in a circle in a forest glade. Each holds a small amount of hot chicken broth.",
  "A new, bright purple mushroom has sprouted from the base of a hemlock tree. Every several seconds, it puffs out a cloud of spores. Are the trees starting to look purple to you?",
  "A group of bandits rushes into town. Turns out, while waiting to ambush hapless travelers, THEY got ambushed! Are they worth helping out?",
  "A little girl is watching you from the trees. The next time you glance over, you see a wolf run away.",
  "The trees have linked their branches together in a network fashion, and they’re sending communications incredibly quickly throughout the forest. Some people want to take advantage of this new development.",
  "The king orders that large sections of the forest be cleared out to make way for construction of his state-of-the-art summer resort. Lots of citizens want it, but there is an equally-sized group that doesn’t.",
  "A worn rope hangs down from one of the tallest trees in the forest. It seems sturdy enough…",
];
// TODO: separate occuptations from faction from descriptive
const OCCUPATION = [
  "thief",
  "rider",
  "soldier",
  "fortune seeker",
  "bandit",
  "slave trader",
  "assassin",
  "smith",
  "gravedigger",
  "rust brother",
  "town drunk",
  "shepherd",
  "braggart",
  "cook",
  "cultist",
  "guard",
  "messenger",
  "miner",
  "academic",
  "treasure hunter",
  "beggar",
  "actor",
  "lumberjack",
  "hunter",
  "farmer",
  "laborer",
  "jester",
  "wanderer",
  "fisher",
  "noble",
  "trader",
  "brewer",
  "carpenter",
  "apprentice",
  "thief",
  "druid",
  "baker",
  "refugee",
];
// todo: city occuptations
const CHARACTERISTIC_ADJ = [
  "hateful",
  "graceful",
  "towering",
  "cocky",
  "constantly smiling",
  "perfumed",
  "sullen",
  "lovesick",
  "elegant",
  "sweaty",
  "drunk",
  "wiry",
  "very tired",
  "lazy",
  "seducing",
  "fat",
  "foppish",
  "very beautiful",
  "suspicious",
  "desperate",
  "tattooed",
];
const CHARACTERISTIC = [
  "with fluffy hair",
  "with ice blue eyes",
  "with a scarred face",
  "with a severed ear",
  "with an eye patch",
  "who is missing teeth",
  "with an impressive beard or hair",
  "with round cheeks",
  "with a distinct birthmark",
  "sporting strange facial paint",
  "with sad eyes",
  "who smells bad",
  "who is constantly joking",
  "who is constantly eating",
  "with unkempt eyebrows",
];
// todo: remove quirks that PCs cannot see and create SECRET array instead
const QUIRKS = [
  "likes to scare people",
  "wants revenge more than anything",
  "has doubts",
  "is curious about killing; maybe too curious",
  "likes to touch people as if old friends",
  "is a brilliant storyteller",
  "will take over, one day",
  "has a craving for a mug of beer",
  "believes he or she is being followed",
  "swears all the time",
  "has a theory about the world. Wants to tell everyone about it",
  "knows a lot about people. Gossipy",
  "is a notorious cheat",
  "believes self to be of royal lineage",
  "has expensive habits. Leaves tab to others",
  "will do anything to achieve dream. Anything",
  "hates a competitor and will do anything to get rid of him or her",
  "is bankrupt, but has a grand plan to save the business. Just needs some help",
  "is planning to avenge dead parent",
  "is possessed by a quirky demon",
  "worships the god in the deep",
  "is the only survivor of a burnt down village. Pyromaniac",
  "is a legendary pickpocket constantly changing identities",
  "is a cultist, looking for new victims",
  "is obsessed with finding a special monster. Will not give up until one of them is dead",
  "is squeamish and weepy",
  "sleeps badly, sees holy visions at night",
  "is too sensitive for this cruel world",
  "is an Alder spy in disguise. Will not hesitate to kill",
  "is very enthusiastic. Has a treasure map but no surviving friends",
  "is chewing on narcotic leaves, staring glare and foul mood",
  "is haunted by dreams of a family dying in a fire. Sometimes hallucinates",
  "is dreaming about a family and a house. Will do anything to realize it",
  "is skilled at gambling. Booted from three villages",
  "is interested in poetry",
  "hides a dark secret",
];
const SECRETS = ["secretly dreams of killing someone"];

const KIN_BITTER_REACH = [
  {
    name: "human",
    dist: 20,
    cultures: [
      "ailander",
      "alderlander",
      "galdane",
      "quard",
      "misgrown",
      "sourdough",
    ],
  },
  {
    name: "dwarf",
    dist: 8,
    cultures: [
      "gatekeeper",
      "pathkeeper",
      "forgethrall",
      "belderan",
      "canide",
      "crombe",
      "merromannian",
      "valondian",
      "skemade",
    ],
  },
  {
    name: "elf",
    dist: 15,
    cultures: ["melder", "unruly", "frailer", "elvenspring"],
  },
  {
    name: "orc",
    dist: 5,
    cultures: ["wolfhowl", "frostwind", "bearskull", "drifter"],
  },
  { name: "wolfkin", dist: 3, cultures: null },
  { name: "goblin", dist: 8, cultures: null },
  { name: "saurian", dist: 0, cultures: null },
  { name: "saurian", dist: 0, cultures: null },
];
const CULTURES_BITTER_REACH = {
  human: [
    { name: "ailander", dist: 10 },
    { name: "alderlander", dist: 20 },
    { name: "galdane", dist: 10 },
    { name: "quard", dist: 10 },
    { name: "misgrown", dist: 3 },
    { name: "sourdough", dist: 47 },
  ],
  dwarf: [
    { name: "gatekeeper", dist: 35 },
    { name: "pathkeeper", dist: 34 },
    { name: "forgethrall", dist: 1 },
    { name: "belderan", dist: 5 },
    { name: "canide", dist: 5 },
    { name: "crombe", dist: 5 },
    { name: "merromannian", dist: 5 },
    { name: "valondian", dist: 5 },
    { name: "skemade", dist: 5 },
  ],
  elf: [
    { name: "melder", dist: 2 },
    { name: "unruly", dist: 28 },
    { name: "frailer", dist: 60 },
    { name: "elvenspring", dist: 10 },
  ],
  orc: [
    { name: "wolfhowl", dist: 25 },
    { name: "frostwind", dist: 25 },
    { name: "bearskull", dist: 25 },
    { name: "drifter", dist: 25 },
  ],
  wolfkin: null,
  goblin: null,
  sherpa: null,
};

const KIN_FORBIDDEN_LANDS = [];

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function getRandomItem(data) {
  let x = getRandomInt(0, data.length - 1);
  let result = data[x];
  if (result === undefined) {
    result = "";
  }
  return result;
}
function buildDistribution(data) {
  console.log("build distribution");
  console.log(data);
  let dist = [];
  data.forEach((x) => {
    for (i = 0; i < x.dist; i++) {
      dist.push(x.name);
    }
  });
  return dist;
}
function getRandomInt(min = 1, max = 100) {
  min = Math.ceil(min);
  max = Math.floor(max);
  const result = Math.floor(Math.random() * (max - min + 1)) + min;
  return result;
}

function getNPCCharacteristics() {
  let occupation = getRandomItem(OCCUPATION);
  let adj = getRandomItem(CHARACTERISTIC_ADJ);
  let characteristic = getRandomItem(CHARACTERISTIC);
  let quirk = getRandomItem(QUIRKS);
  return {
    occupation: occupation,
    adjective: adj,
    characteristic: characteristic,
    quirk: quirk,
  };
}

/*
let data dict drive providing values that we don't want to generate; otherwise
generate values and return formatted string.
todo: could return dict and/or call helper that has different format strings
 */
function getNPC(data) {
  let kin = data ? data.kin : getRandomKin();
  console.log(`kin here is: ${kin}`);
  let gender = data ? data.gender : getRandomGender();
  console.log("KIN FROM DATA: " + kin);
  let kin_cultures = CULTURES_BITTER_REACH[kin]
    ? buildDistribution(CULTURES_BITTER_REACH[kin])
    : [];
  let culture = getRandomItem(kin_cultures);

  // getName expects are kin that can must be culture for human and frailer/elvenspring/elf for elf and ignore others
  let kinToPass = kin;
  if (kin == "human") {
    console.log("human kin with culture: " + culture);
    if (culture == "quard" || culture == "galdane") {
      kinToPass = "aslene";
    } else {
      kinToPass = culture;
    }
  } else if (kin == "elf") {
    if (culture == "melder" || culture == "unruly") {
      kinToPass = "elf";
    } else {
      kinToPass = culture;
    }
  } else if (kin == "forgethrall") {
    kinToPass = "dwarf";
  } else if (kin == "sherpa") {
    kinToPass = "sherpa";
  }
  console.log("KIN TO PASS: " + kinToPass);
  console.log(gender);
  let name = getName(gender, kinToPass);

  let characteristics = getNPCCharacteristics();
  let message = `${name} is ${gender} ${culture} ${kin} who is a ${characteristics.adjective} ${characteristics.occupation} ${characteristics.characteristic} who ${characteristics.quirk}.`;
  // todo update to return just an object and force caller to build messsage
  message = message.trim();
  return { message, name };
}

function getRandomGender() {
  return getRandomItem(["male", "female", "asexual"]);
}
function getRandomKin() {
  let kin_names = buildDistribution(KIN_BITTER_REACH);
  let kin_name = getRandomItem(kin_names);
  return KIN_BITTER_REACH.filter((x) => x.name == kin_name)[0].name;
}

function getRandomItemByDistribution(distributionListName) {
  let listItems = buildDistribution(distributionListName);
  let listItem = getRandomItem(listItems);
  return distributionListName.filter((x) => x.name == listItem)[0].name;
}

function chatMessagePublic(message) {
  ChatMessage.create({
    content: message,
  });
}

function chatMessage(message) {
  ChatMessage.create({
    user: game.user._id,
    whisper: game.users.filter((u) => u.isGM).map((u) => u._id),
    content: message,
  });
}
function showDialog(args) {
  new Dialog({
    title: "Generate Weather",
    content: myContent,
    buttons: {
      yes: {
        icon: "<i class='fas fa-check'></i>",
        label: `Apply Changes`,
      },
    },
    default: "yes",
    update: {},
    close: (x) => {
      ChatMessage.create({
        user: game.user._id,
        speaker: ChatMessage.getSpeaker({ token: actor }),
        content: args,
      });
    },
  }).render(true);
}
/*
 * function to extract expression between curly braces and evaluate as dice roll
 * ex: 2d6+4
 * only understands number of dice, capital D, dice face and an option plus expression
 * todo: smarter about subtract and other stuff as needed
 * */
function embeddedRoll(input) {
  var diceRegEx = /{([^}]+)}/;
  let found = input.match(diceRegEx);
  if (!found) {
    return input;
  }
  let diceExpression = found[1].replace(/\s/g, ""); //get found expression and remove spaces
  let dice = diceExpression.split("D");
  let numDice = dice[0] === "" ? "1" : dice[0];
  let faceAndPlus = dice[1].split("+");
  let faceDice = faceAndPlus[0].replace(/\s/g, "");
  let plusAmount = faceAndPlus[1];
  if (!plusAmount) {
    plusAmount = 0;
  } else {
    plusAmount.replace(/\s/g, "");
  }
  let total = 0;
  for (let x = 0; x < numDice; x++) {
    let result = Math.floor(Math.random() * faceDice) + 1;
    total += result;
  }
  total += parseInt(plusAmount);
  return input.replace(found[0], total);
}

function toTitleCase(str) {
  return str
    .toLowerCase()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
